name: My First Robot

on:
  workflow_dispatch:

  schedule:
    - cron: '0 12 * * *'

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: |
          echo "Robot Butler"
          echo "Today is $(date)"
          date
