name: Robot Butler

on:
  workflow_dispatch:

  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        run: ls -la

      - name: Run Python
        run: python robot.py

      - name: Commit updated memory
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add latest_video.txt

          git diff --cached --quiet || git commit -m "Update latest_video.txt"

          git push
