name: My First Robot

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: |
          echo "Hello!"
          echo "My robot is alive."
          date
